### ISSUE TITLE
Missing key property in BarStack

### ISSUE THREAD

**Issue by JesHansen** [react-d3/react-d3-shape#11]
I've encountered the following warning seen in the Chrome console when using the BarStackChart from react-d3-basic:

**warning.js?c790:45 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `BarStack`. See https://fb.me/react-warning-keys for more information.**

It looks like the return statement (return _react2.default.createElement ...) of the function _mkBarStack in react-d3-shape\lib\components\bar_stack.js doesn't set a key property on the elements returned.

**Comment by JesperKihlberg** [comment]
This is also the case in Bar and BarHorizontal.

**Comment by fysheets** [comment]
@Udokah - Since this was closed, I was wondering what the resolution was, or if it was closed but not resolved?  Seeing the issue with AreaStack.

**Comment by svet93** [comment]
I too see the problem with BarStack
